default-image-path: /cogules/Mothership:Site/images/default.jpg # Path to default image for resizing, relative to public/web path
salt: rCWj^/P8HXMKAru6xX4;(YyP7HTvZutzzEAqoxM9M&Ip+K{{Lot 7g*ZiGR@g>-@